KEYWORD_ACTIONS = {
    "activate",
    "attach",
    "behold",
    "cast",
    "counter",
    "create",
    "destroy",
    "discard",
    "double",
    "triple",
    "exchange",
    "exile",
    "fight",
    "goad",
    "investigate",
    "mill",
    "play",
    "regenerate",
    "reveal",
    "sacrifice",
    "scry",
    "search",
    "shuffle",
    "surveil",
    "tap",
    "untap",
    "transform",
    "convert",
    "fateseal",
    "clash",
    "planeswalk",
    "set in motion",
    "abandon",
    "proliferate",
    "detain",
    "populate",
    "monstrosity",
    "vote",
    "bolster",
    "manifest",
    "support",
    "meld",
    "exert",
    "explore",
    "assemble",
    "adapt",
    "amass",
    "learn",
    "venture into the dungeon",
    "connive",
    "open an attraction",
    "roll to visit your attractions",
    "incubate",
    "the ring tempts you",
    "face a villainous choice",
    "time travel",
    "discover",
    "cloak",
    "collect evidence",
    "suspect",
    "forage",
    "manifest dread",
    "endure",
}
