# This is a complete list matching the MTG comprehensive rules as of
# 2025-09-19

# Section 207.2c
ABILITY_WORDS = {
    "battalion",
    "bloodrush",
    "channel",
    "chroma",
    "domain",
    "fateful hour",
    "grandeur",
    "hellbent",
    "heroic",
    "imprint",
    "join forces",
    "kinship",
    "landfall",
    "metalcraft",
    "morbid",
    "radiance",
    "sweep",
    "tempting offer",
    "threshold",
}

# Section 701
KEYWORD_ACTIONS = {
    "activate",
    "attach",
    "behold",
    "cast",
    "counter",
    "create",
    "destroy",
    "discard",
    "double",
    "triple",
    "exchange",
    "exile",
    "fight",
    "goad",
    "investigate",
    "mill",
    "play",
    "regenerate",
    "reveal",
    "sacrifice",
    "scry",
    "search",
    "shuffle",
    "surveil",
    "tap",
    "untap",
    "transform",
    "convert",
    "fateseal",
    "clash",
    "planeswalk",
    "set in motion",
    "abandon",
    "proliferate",
    "detain",
    "populate",
    "monstrosity",
    "vote",
    "bolster",
    "manifest",
    "support",
    "meld",
    "exert",
    "explore",
    "assemble",
    "adapt",
    "amass",
    "learn",
    "venture into the dungeon",
    "connive",
    "open an attraction",
    "roll to visit your attractions",
    "incubate",
    "the ring tempts you",
    "face a villainous choice",
    "time travel",
    "discover",
    "cloak",
    "collect evidence",
    "suspect",
    "forage",
    "manifest dread",
    "endure",
    "harness",
}

# Section 702
KEYWORD_ABILITIES = {
    "deathtouch",
    "defender",
    "double strike",
    "enchant",
    "equip",
    "first strike",
    "flash",
    "flying",
    "haste",
    "hexproof",
    "indestructible",
    "intimidate",
    "landwalk",
    "lifelink",
    "protection",
    "vigilance",
    "ward",
    "banding",
    "rampage",
    "cumulative upkeep",
    "flanking",
    "phasing",
    "buyback",
    "shadow",
    "cycling",
    "echo",
    "horsemanship",
    "fading",
    "kicker",
    "flashback",
    "madness",
    "fear",
    "morph",
    "amplify",
    "provoke",
    "storm",
    "affinity",
    "entwine",
    "modular",
    "sunburst",
    "bushido",
    "soulshift",
    "splice",
    "offering",
    "ninjutsu",
    "epic",
    "convoke",
    "dredge",
    "transmute",
    "bloodthirst",
    "haunt",
    "replicate",
    "forecast",
    "graft",
    "recover",
    "ripple",
    "split second",
    "suspend",
    "vanishing",
    "absorb",
    "aura swap",
    "delve",
    "fortify",
    "frenzy",
    "gravestorm",
    "poisonous",
    "champion",
    "changeling",
    "evoke",
    "hideaway",
    "prowl",
    "reinforce",
    "conspire",
    "persist",
    "wither",
    "retrace",
    "devour",
    "unearth",
    "cascade",
    "annihilator",
    "level up",
    "rebound",
    "umbra armor",
    "infect",
    "battle cry",
    "living weapon",
    "undying",
    "miracle",
    "soulbound",
    "overload",
    "scavenge",
    "unleash",
    "cipher",
    "evolve",
    "extort",
    "fuse",
    "bestow",
    "trubute",
    "dethrone",
    "hidden agenda",
    "outlast",
    "prowess",
    "dash",
    "exploit",
    "menace",
    "renown",
    "awaken",
    "devoid",
    "ingest",
    "myriad",
    "surge",
    "skulk",
    "emerge",
    "escalate",
    "melee",
    "crew",
    "fabricate",
    "partner",
    "undaunted",
    "improvise",
    "aftermath",
    "embalm",
    "eternalize",
    "afflict",
    "ascend",
    "assist",
    "jump-start",
    "mentor",
    "afterlife",
    "riot",
    "spectacle",
    "escape",
    "companion",
    "mutate",
    "encore",
    "boast",
    "foretell",
    "demonstrate",
    "daybound",
    "nightbound",
    "disturb",
    "decayed",
    "cleave",
    "training",
    "compleated",
    "reconfigure",
    "blitz",
    "casualty",
    "enlist",
    "read ahead",
    "ravenous",
    "squad",
    "space sculptor",
    "visit",
    "prototype",
    "living metal",
    "more than meets the eye",
    "for mirrodin!",
    "toxic",
    "backup",
    "bargain",
    "craft",
    "disguise",
    "solved",
    "plot",
    "saddle",
    "spree",
    "freerunning",
    "gift",
    "offspring",
    "impending",
    "exhaust",
    "max speed",
    "start your engines!",
    "harmonize",
    "mobilize",
    "job select",
    "tiered",
    "station",
    "warp",
    "∞",
    "mayhem",
    "web-slinging",
}
